"use client";

import "./experiment-execution.css";
import "./execution-history.css";

import { ArrowLeftIcon, ChartLineIcon, CircleNotchIcon, PauseIcon, PlayIcon, StopIcon } from "@phosphor-icons/react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import { StatusBadge } from "@/components/ui/StatusBadge";
import { engineering } from "@/lib/format";
import { formatExecutionStatus, formatResultStatus, getMeasurementDisplayName, getMeasurementUnit, getParameterDisplayName } from "@/lib/presentation";
import type { Experiment } from "@/lib/types";

export function ExperimentExecution({ experiment, onAnalyze, onBack, onPause, onResume, onRun, onStop }: { experiment: Experiment; onAnalyze?: () => void; onBack: () => void; onPause: () => void; onResume: () => void; onRun: () => void; onStop: () => void }) {
  const results = experiment.run_results ?? [];
  const total = experiment.generated_runs?.length ?? 0;
  const complete = results.filter((result) => result.status === "COMPLETED").length;
  const failed = results.filter((result) => result.status === "FAILED").length;
  const skipped = results.filter((result) => result.status === "SKIPPED").length;
  const remaining = Math.max(0, total - results.length);
  const latest = results.at(-1);
  const paused = experiment.execution_status === "paused";
  const active = experiment.execution_status === "running" || paused;
  const hasHistory = results.length > 0;
  const percentage = total ? (results.length / total) * 100 : 0;
  const metricKey = results.find((result) => Object.keys(result.measurements ?? {}).length)?.measurements ? Object.keys(results.find((result) => Object.keys(result.measurements ?? {}).length)!.measurements!)[0] : "";
  const chartData = results.filter((result) => result.status === "COMPLETED" && typeof result.measurements?.[metricKey] === "number").map((result) => ({ run: result.run_index, value: result.measurements?.[metricKey] }));
  const outcome = latest?.requirement_results?.some((item) => item.status === "FAIL") ? "FAIL" : latest?.requirement_results?.length && latest.requirement_results.every((item) => item.status === "PASS") ? "PASS" : latest?.status;
  const elapsedSeconds = experiment.started_at ? Math.max(0, (Date.now() - new Date(experiment.started_at).getTime()) / 1_000) : null;
  const estimatedSeconds = elapsedSeconds !== null && results.length > 0 && remaining > 0 ? (elapsedSeconds / results.length) * remaining : null;
  const duration = (seconds: number | null) => seconds === null ? "Not available" : seconds < 60 ? `${Math.round(seconds)} s` : `${Math.floor(seconds / 60)} min ${Math.round(seconds % 60)} s`;
  const timestamp = (value?: string | null) => value ? new Date(value).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit", second: "2-digit" }) : "Not recorded";
  const hasRequirements = Boolean(experiment.requirement_definitions?.length);

  return <section className="execution-screen">
    <header className="execution-header"><div><button className="execution-back" onClick={onBack} type="button"><ArrowLeftIcon aria-hidden size={14} />Experiments</button><h2>{experiment.name ?? experiment.hypothesis}</h2><span>{experiment.circuit_snapshot?.name ?? "Circuit"} · Revision {experiment.circuit_revision}</span></div><div><StatusBadge tone={active ? "warning" : experiment.execution_status === "failed" ? "danger" : experiment.execution_status === "completed" ? "success" : "neutral"}>{formatExecutionStatus(experiment.execution_status)}</StatusBadge>{active ? <><button className="button button--secondary" onClick={paused ? onResume : onPause} type="button">{paused ? <PlayIcon aria-hidden size={14} /> : <PauseIcon aria-hidden size={14} />}{paused ? "Resume" : "Pause"}</button><button className="button button--danger" onClick={onStop} type="button"><StopIcon aria-hidden size={14} />Stop</button></> : hasHistory && onAnalyze ? <button className="button button--secondary" onClick={onAnalyze} type="button"><ChartLineIcon aria-hidden size={14} />View Analysis</button> : <button className="button button--primary" disabled={!total} onClick={onRun} type="button"><PlayIcon aria-hidden size={14} />Run Experiment</button>}</div></header>
    <section className="execution-progress" aria-label="Execution progress"><div><span>Run {results.length} of {total}</span><strong>{percentage.toFixed(1)}%</strong></div><div aria-valuemax={total} aria-valuemin={0} aria-valuenow={results.length} className="progress-track" role="progressbar"><span style={{ width: `${percentage}%` }} /></div><div className="execution-timing"><span>Elapsed <strong>{duration(elapsedSeconds)}</strong></span><span>Estimated remaining <strong>{active ? duration(estimatedSeconds) : "Complete"}</strong></span></div></section>
    <section className="execution-provenance" aria-label="Run traceability"><div><span>Collection</span><strong>{experiment.collection_name || "Unfiled"}</strong></div><div><span>Run by</span><strong>{experiment.run_by || "Not recorded"}</strong></div><div><span>Started</span><strong>{timestamp(experiment.started_at)}</strong></div><div><span>Ended</span><strong>{timestamp(experiment.completed_at)}</strong></div>{experiment.notes ? <div className="execution-provenance__notes"><span>Notes</span><strong>{experiment.notes}</strong></div> : null}</section>
    <div className="execution-main"><section className="execution-response"><header><h3>Live response</h3><span>{metricKey ? `${getMeasurementDisplayName(metricKey)} (${getMeasurementUnit(metricKey) || "unitless"})` : "Measurement trace"}</span></header>{chartData.length ? <ResponsiveContainer height="100%" width="100%"><LineChart data={chartData} margin={{ top: 12, right: 24, bottom: 18, left: 8 }}><CartesianGrid stroke="var(--color-divider)" strokeDasharray="2 3" vertical={false} /><XAxis dataKey="run" label={{ value: "Run", position: "insideBottom", offset: -8 }} tickLine={false} axisLine={{ stroke: "var(--color-border-strong)" }} /><YAxis label={{ angle: -90, position: "insideLeft", value: getMeasurementUnit(metricKey) || "Value" }} tickFormatter={(value) => engineering(Number(value), getMeasurementUnit(metricKey))} tickLine={false} axisLine={{ stroke: "var(--color-border-strong)" }} width={72} /><Tooltip formatter={(value) => engineering(Number(value), getMeasurementUnit(metricKey))} labelFormatter={(value) => `Run ${String(value).padStart(3, "0")}`} /><Line dataKey="value" dot={false} isAnimationActive={false} stroke="var(--color-accent)" strokeWidth={2} type="linear" /></LineChart></ResponsiveContainer> : <div className="execution-chart-empty"><ChartLineIcon aria-hidden size={24} /><strong>No response recorded</strong><p>The chart will update as simulation runs complete.</p></div>}</section><aside className="current-run"><header><h3>{active ? "Latest completed run" : "Final recorded run"}</h3><span>{latest ? String(latest.run_index).padStart(3, "0") : "Not started"}</span></header>{latest ? <><div className="current-run__section"><h4>Inputs</h4>{Object.entries(latest.parameters).map(([key, value]) => { const [componentId, parameter = ""] = key.split("."); return <div className="execution-row" key={key}><span>{getParameterDisplayName(componentId, parameter)}</span><strong>{engineering(value, experiment.variables?.find((variable) => `${variable.component_id}.${variable.parameter}` === key)?.unit)}</strong></div>; })}</div><div className="current-run__section"><h4>Measurements</h4>{Object.entries(latest.measurements ?? {}).map(([key, value]) => <div className="execution-row" key={key}><span>{getMeasurementDisplayName(key)}</span><strong>{engineering(value, getMeasurementUnit(key))}</strong></div>)}</div><div className="current-run__result"><span>Result</span><StatusBadge tone={outcome === "PASS" ? "success" : outcome === "FAIL" || outcome === "FAILED" ? "danger" : "neutral"}>{hasRequirements ? formatResultStatus(outcome) : "Not classified"}</StatusBadge></div></> : <p className="empty-copy">Start the experiment to inspect the active configuration.</p>}</aside></div>
    <div className="execution-counts"><span>Completed <strong>{complete}</strong></span>{hasRequirements ? <><span className="is-pass">Passing <strong>{results.filter((result) => result.requirement_results?.length && result.requirement_results.every((item) => item.status === "PASS")).length}</strong></span><span className="is-fail">Failing <strong>{results.filter((result) => result.requirement_results?.some((item) => item.status === "FAIL")).length}</strong></span></> : <span>Classification <strong>Not configured</strong></span>}<span>Errors <strong>{failed}</strong></span><span>Remaining <strong>{remaining}</strong></span>{skipped ? <span>Skipped <strong>{skipped}</strong></span> : null}</div>
    {active && <div className="execution-running">{paused ? <PauseIcon aria-hidden size={16} /> : <CircleNotchIcon aria-hidden className="loading-mark" size={16} />}{paused ? "Execution paused. Completed runs are preserved; resume to continue the remaining plan." : "Running simulations. Results update after each completed run."}</div>}
    {hasHistory && !active && <p className="execution-history-note">Recorded runs are preserved. Create a new experiment to execute a revised test plan.</p>}
    {failed > 0 && <section className="execution-errors"><h3>Simulation errors</h3>{results.filter((result) => result.status === "FAILED").slice(-5).map((result) => <div key={result.run_index}><strong>Run {String(result.run_index).padStart(3, "0")}</strong><span>{result.error ?? "The simulator did not complete this configuration."}</span></div>)}</section>}
    <section className="execution-plan"><header><h3>Recent runs</h3><span>{results.length} recorded</span></header>{results.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Run</th>{experiment.variables?.map((variable) => <th key={variable.label}>{getParameterDisplayName(variable.component_id, variable.parameter)}</th>)}{metricKey ? <th>{getMeasurementDisplayName(metricKey)}</th> : null}<th>Started</th><th>Ended</th><th>Run by</th><th>Status</th></tr></thead><tbody>{results.slice(-12).reverse().map((result) => <tr key={result.run_index}><td className="numeric-column">{String(result.run_index).padStart(3, "0")}</td>{experiment.variables?.map((variable) => { const key = `${variable.component_id}.${variable.parameter}`; return <td className="numeric-column" key={key}>{engineering(result.parameters[key], variable.unit)}</td>; })}{metricKey ? <td className="numeric-column">{typeof result.measurements?.[metricKey] === "number" ? engineering(result.measurements[metricKey], getMeasurementUnit(metricKey)) : "Not available"}</td> : null}<td>{timestamp(result.started_at)}</td><td>{timestamp(result.completed_at)}</td><td>{result.run_by || "Not recorded"}</td><td>{formatResultStatus(result.status)}</td></tr>)}</tbody></table></div> : <p className="empty-copy">No runs have been executed.</p>}</section>
  </section>;
}
