"use client";

import "./experiment-report.css";

import { useMemo } from "react";
import { ArrowLeftIcon, DownloadSimpleIcon, PrinterIcon } from "@phosphor-icons/react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import { engineering } from "@/lib/format";
import { formatCriterionDefinition, formatExperimentType, getComponentDisplayName, getMeasurementDisplayName, getMeasurementUnit, getParameterDisplayName, getParameterUnit } from "@/lib/presentation";
import type { Circuit, Experiment, ExperimentRunResult } from "@/lib/types";
import { StaticCircuitSchematic } from "@/components/CircuitCanvas";

type Metric = { key: string; label: string; unit: string };
const parameterKey = (componentId: string, parameter: string) => `${componentId}.${parameter}`;
const resultLabel = (run: ExperimentRunResult) => { const criteria = run.requirement_results ?? []; if (!criteria.length) return "Not classified"; if (criteria.some((result) => result.status === "FAIL")) return "Fail"; return criteria.every((result) => result.status === "PASS") ? "Pass" : "Not evaluated"; };
const metricFor = (key: string): Metric => ({ key, label: getMeasurementDisplayName(key), unit: getMeasurementUnit(key) });
function download(filename: string, content: string, mime: string) { const anchor = document.createElement("a"); const url = URL.createObjectURL(new Blob([content], { type: mime })); anchor.href = url; anchor.download = filename; document.body.append(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1_000); }
function circuitFingerprint(circuit: Circuit) { const source = JSON.stringify({ components: circuit.components, nodes: circuit.nodes, metadata: circuit.metadata }); let hash = 2166136261; for (let index = 0; index < source.length; index += 1) { hash ^= source.charCodeAt(index); hash = Math.imul(hash, 16777619); } return `FNV1A-${(hash >>> 0).toString(16).padStart(8, "0").toUpperCase()}`; }

function ReportHeatmap({ experiment, metric, runs }: { experiment: Experiment; metric: Metric; runs: ExperimentRunResult[] }) {
  const [xVariable, yVariable] = experiment.variables ?? [];
  const xKey = parameterKey(xVariable.component_id, xVariable.parameter);
  const yKey = parameterKey(yVariable.component_id, yVariable.parameter);
  const xLevels = [...new Set(runs.map((run) => run.parameters[xKey]))].sort((a, b) => a - b);
  const yLevels = [...new Set(runs.map((run) => run.parameters[yKey]))].sort((a, b) => a - b);
  const values = runs.map((run) => run.measurements?.[metric.key]).filter((value): value is number => typeof value === "number");
  const minimum = Math.min(...values);
  const maximum = Math.max(...values);
  return <figure className="report-heatmap"><figcaption>{metric.label} across the two-variable sweep</figcaption><div className="report-table-scroll"><table><thead><tr><th>{getParameterDisplayName(yVariable.component_id, yVariable.parameter)} ↓ / {getParameterDisplayName(xVariable.component_id, xVariable.parameter)} →</th>{xLevels.map((value) => <th key={value}>{engineering(value, xVariable.unit)}</th>)}</tr></thead><tbody>{yLevels.map((y) => <tr key={y}><th>{engineering(y, yVariable.unit)}</th>{xLevels.map((x) => { const run = runs.find((candidate) => candidate.parameters[xKey] === x && candidate.parameters[yKey] === y); const value = run?.measurements?.[metric.key]; const intensity = typeof value === "number" ? maximum === minimum ? .42 : .12 + ((value - minimum) / (maximum - minimum)) * .68 : 0; const result = run ? resultLabel(run) : "Not available"; return <td aria-label={`${getParameterDisplayName(xVariable.component_id, xVariable.parameter)} ${engineering(x, xVariable.unit)}. ${getParameterDisplayName(yVariable.component_id, yVariable.parameter)} ${engineering(y, yVariable.unit)}. ${metric.label}: ${typeof value === "number" ? engineering(value, metric.unit) : "Not available"}. Result: ${result}.`} className={`report-heatmap__cell ${result === "Fail" ? "is-fail" : result === "Pass" ? "is-pass" : ""}`} key={x} style={typeof value === "number" ? { backgroundColor: `rgba(47, 107, 87, ${intensity})` } : undefined}>{typeof value === "number" ? <><span>{engineering(value, metric.unit)}</span><small>{result}</small></> : "Not available"}</td>; })}</tr>)}</tbody></table></div><div className="report-heatmap__legend"><span>{engineering(minimum, metric.unit)}</span><i /><i /><i /><i /><i /><span>{engineering(maximum, metric.unit)}</span><b>Dashed outline: requirement failed</b></div></figure>;
}

export function ExperimentReport({ experiment, onBack }: { experiment: Experiment; onBack: () => void }) {
  const runs = useMemo(() => (experiment.run_results ?? []).filter((run) => run.status === "COMPLETED"), [experiment]);
  const metrics = useMemo(() => [...new Set(runs.flatMap((run) => Object.entries(run.measurements ?? {}).filter(([, value]) => typeof value === "number" && Number.isFinite(value)).map(([key]) => key)))].map(metricFor), [runs]);
  const variables = experiment.variables ?? [];
  const primaryMetric = metrics[0];
  const primaryVariable = variables.length === 1 ? variables[0] : null;
  const chartKey = primaryVariable ? parameterKey(primaryVariable.component_id, primaryVariable.parameter) : "";
  const chartRows = primaryMetric && primaryVariable ? [...runs].filter((run) => typeof run.measurements?.[primaryMetric.key] === "number").sort((a, b) => a.parameters[chartKey] - b.parameters[chartKey]).map((run) => ({ variable: run.parameters[chartKey], value: Number(run.measurements?.[primaryMetric.key]) })) : [];
  const failedRuns = (experiment.run_results ?? []).filter((run) => run.status === "FAILED");
  const evaluated = runs.filter((run) => resultLabel(run) !== "Not classified");
  const passed = runs.filter((run) => resultLabel(run) === "Pass");
  const reportName = (experiment.name ?? experiment.hypothesis).replaceAll(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "experiment";
  const csv = useMemo(() => rawCsv(experiment, runs, metrics), [experiment, metrics, runs]);

  return <section className="report-viewer"><header className="report-toolbar"><button className="button button--tertiary" onClick={onBack} type="button"><ArrowLeftIcon aria-hidden size={14} />All Reports</button><div><button className="button button--secondary" onClick={() => window.print()} type="button"><PrinterIcon aria-hidden size={14} />Print / PDF</button><button className="button button--secondary" onClick={() => download(`${reportName}-raw-data.csv`, csv, "text/csv;charset=utf-8")} type="button"><DownloadSimpleIcon aria-hidden size={14} />CSV</button><button className="button button--secondary" onClick={() => download(`${reportName}-report.json`, JSON.stringify(experiment, null, 2), "application/json")} type="button"><DownloadSimpleIcon aria-hidden size={14} />JSON</button></div></header><article className="report-document"><header className="report-title"><p>Virtual Electronics Laboratory</p><h1>{experiment.circuit_snapshot.name}</h1><h2>{experiment.name ?? experiment.hypothesis}</h2><dl><div><dt>Experiment</dt><dd>{experiment.id}</dd></div><div><dt>Circuit revision</dt><dd>{experiment.circuit_revision}</dd></div><div><dt>Executed</dt><dd>{new Date(experiment.completed_at ?? experiment.created_at).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</dd></div></dl></header>
    <ReportSection number="1" title="Experiment Objective"><p>{experiment.description || experiment.hypothesis || "No objective was recorded."}</p></ReportSection>
    <ReportSection number="2" title="Circuit Under Test"><StaticCircuitSchematic circuit={experiment.circuit_snapshot} /><p className="report-caption">Figure 1. Recorded topology for {experiment.circuit_snapshot.name}, Revision {experiment.circuit_revision}.</p><table className="report-table"><thead><tr><th>Reference</th><th>Component</th><th>Recorded values</th><th>Connections</th></tr></thead><tbody>{experiment.circuit_snapshot.components.map((component) => <tr key={component.id}><td className="report-mono">{component.id}</td><td>{getComponentDisplayName(component.type)}</td><td>{Object.entries(component.params).map(([key, value]) => typeof value === "number" ? `${getParameterDisplayName(component.id, key)}: ${engineering(value, getParameterUnit(key))}` : `${key}: ${String(value)}`).join(", ") || "None"}</td><td>{Object.entries(component.pins).map(([pin, node]) => `${pin}: ${node ?? "unconnected"}`).join(", ")}</td></tr>)}</tbody></table></ReportSection>
    <ReportSection number="3" title="Experiment Setup"><div className="report-two-column"><div><h4>Variables</h4>{variables.length ? variables.map((variable) => <div className="report-property" key={variable.label}><span>{getParameterDisplayName(variable.component_id, variable.parameter)}</span><strong>{engineering(variable.start, variable.unit)} to {engineering(variable.stop, variable.unit)}, {variable.points} values</strong></div>) : <p>No parameters were varied.</p>}</div><div><h4>Measurements</h4>{experiment.measurement_definitions?.map((measurement) => <div className="report-property" key={measurement}><span>{getMeasurementDisplayName(measurement)}</span><strong>Recorded each run</strong></div>)}<h4 className="report-subheading">Acceptance criteria</h4>{experiment.requirement_definitions?.length ? experiment.requirement_definitions.map((criterion, index) => <div className="report-property" key={index}><span>{getMeasurementDisplayName(criterion.metric)}</span><strong>{formatCriterionDefinition(criterion)}</strong></div>) : <p>No acceptance criteria were defined.</p>}</div></div></ReportSection>
    <ReportSection number="4" title="Test Plan"><div className="report-metadata"><div><span>Experiment type</span><strong>{formatExperimentType(experiment.experiment_type)}</strong></div><div><span>Planned runs</span><strong>{experiment.generated_runs?.length ?? 0}</strong></div><div><span>Completed</span><strong>{runs.length}</strong></div><div><span>Simulation errors</span><strong className={failedRuns.length ? "value-danger" : ""}>{failedRuns.length}</strong></div></div></ReportSection>
    <ReportSection number="5" title="Results"><div className="report-metrics">{metrics.map((metric) => { const values = runs.map((run) => run.measurements?.[metric.key]).filter((value): value is number => typeof value === "number"); return <div key={metric.key}><span>{metric.label}</span><strong>{values.length ? `${engineering(Math.min(...values), metric.unit)} to ${engineering(Math.max(...values), metric.unit)}` : "Not available"}</strong></div>; })}</div>{primaryVariable && primaryMetric ? <figure className="report-chart"><figcaption>{primaryMetric.label} versus {getParameterDisplayName(primaryVariable.component_id, primaryVariable.parameter)}</figcaption><ResponsiveContainer height="100%" width="100%"><LineChart data={chartRows} margin={{ top: 8, right: 20, bottom: 28, left: 12 }}><CartesianGrid stroke="var(--color-divider)" strokeDasharray="2 3" vertical={false} /><XAxis dataKey="variable" label={{ value: `${getParameterDisplayName(primaryVariable.component_id, primaryVariable.parameter)} (${primaryVariable.unit || "unitless"})`, position: "insideBottom", offset: -16 }} tickFormatter={(value) => engineering(Number(value), primaryVariable.unit)} tickLine={false} /><YAxis dataKey="value" label={{ angle: -90, position: "insideLeft", value: `${primaryMetric.label} (${primaryMetric.unit || "unitless"})` }} tickFormatter={(value) => engineering(Number(value), primaryMetric.unit)} tickLine={false} width={82} /><Tooltip formatter={(value) => engineering(Number(value), primaryMetric.unit)} labelFormatter={(value) => engineering(Number(value), primaryVariable.unit)} /><Legend formatter={() => primaryMetric.label} /><Line dataKey="value" dot={{ r: 3 }} name={primaryMetric.label} stroke="var(--color-accent)" strokeWidth={2} type="linear" /></LineChart></ResponsiveContainer></figure> : variables.length === 2 && primaryMetric ? <ReportHeatmap experiment={experiment} metric={primaryMetric} runs={runs} /> : <p>Use the CSV export to inspect the complete recorded data set.</p>}</ReportSection>
    <ReportSection number="6" title="Operating Region and Criteria"><div className="report-metadata"><div><span>Passing configurations</span><strong className="value-pass">{passed.length}</strong></div><div><span>Failing configurations</span><strong className={evaluated.length - passed.length ? "value-danger" : ""}>{evaluated.length - passed.length}</strong></div><div><span>Not classified</span><strong>{runs.length - evaluated.length}</strong></div></div><p className="report-note">Classifications apply only to the sampled configurations in this experiment.</p></ReportSection>
    <ReportSection number="7" title="Configuration Selection"><p>No preferred configuration was automatically selected. Passing status alone does not establish an optimum. Select a run in Analysis after defining the engineering objective.</p></ReportSection>
    <ReportSection number="8" title="Reproducibility Information"><div className="report-two-column"><div className="report-property"><span>Experiment ID</span><strong>{experiment.id}</strong></div><div className="report-property"><span>Circuit revision</span><strong>{experiment.circuit_revision}</strong></div><div className="report-property"><span>Circuit fingerprint</span><strong>{circuitFingerprint(experiment.circuit_snapshot)}</strong></div><div className="report-property"><span>Simulation records</span><strong>{experiment.simulation_ids?.length ? experiment.simulation_ids.join(", ") : "Recorded per run"}</strong></div><div className="report-property"><span>Analysis requested</span><strong>{experiment.measurement_definitions?.some((item) => item.toLowerCase().includes("gain")) ? "Operating point and AC sweep" : "Operating point"}</strong></div><div className="report-property"><span>Input / output nodes</span><strong>{experiment.circuit_snapshot?.metadata.input_node ?? "Not recorded"} / {experiment.circuit_snapshot?.metadata.output_node ?? "Not recorded"}</strong></div><div className="report-property"><span>Execution started</span><strong>{experiment.started_at ? new Date(experiment.started_at).toLocaleString() : "Not recorded"}</strong></div><div className="report-property"><span>Execution completed</span><strong>{experiment.completed_at ? new Date(experiment.completed_at).toLocaleString() : "Not recorded"}</strong></div></div><p className="report-note">Simulator engine and version are not present in the recorded experiment payload and are therefore not asserted by this report.</p></ReportSection>
    <section className="report-section report-appendix"><details><summary>Appendix: Recorded Run Data</summary><p>Previewing the first 20 completed runs. Download CSV for the complete data set.</p><div className="report-table-scroll"><table className="report-table"><thead><tr><th>Run</th>{variables.map((variable) => <th key={variable.label}>{getParameterDisplayName(variable.component_id, variable.parameter)}</th>)}{metrics.map((metric) => <th key={metric.key}>{metric.label}</th>)}<th>Result</th></tr></thead><tbody>{runs.slice(0,20).map((run) => <tr key={run.run_index}><td className="report-mono">{String(run.run_index).padStart(3,"0")}</td>{variables.map((variable) => <td className="report-mono" key={variable.label}>{engineering(run.parameters[parameterKey(variable.component_id, variable.parameter)], variable.unit)}</td>)}{metrics.map((metric) => <td className="report-mono" key={metric.key}>{typeof run.measurements?.[metric.key] === "number" ? engineering(run.measurements[metric.key], metric.unit) : "Not available"}</td>)}<td>{resultLabel(run)}</td></tr>)}</tbody></table></div></details></section>
  </article></section>;
}

function ReportSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="report-section"><h3><span>{number}.</span>{title}</h3>{children}</section>; }
function rawCsv(experiment: Experiment, runs: ExperimentRunResult[], metrics: Metric[]) { const variables = experiment.variables ?? []; const withUnit = (label: string, unit: string) => unit ? `${label} [${unit}]` : label; const headings = ["run", ...variables.map((variable) => withUnit(getParameterDisplayName(variable.component_id, variable.parameter), variable.unit)), ...metrics.map((metric) => withUnit(metric.label, metric.unit)), "result"]; const escape = (value: string | number) => `"${String(value).replaceAll("\"", "\"\"")}"`; return [headings, ...runs.map((run) => [run.run_index, ...variables.map((variable) => run.parameters[parameterKey(variable.component_id, variable.parameter)] ?? ""), ...metrics.map((metric) => run.measurements?.[metric.key] ?? ""), resultLabel(run)])].map((row) => row.map(escape).join(",")).join("\n"); }
