"use client";

import "./experiment-builder.css";
import "./experiment-builder-polish.css";

import { useMemo, useState } from "react";
import { ArrowLeftIcon, CheckCircleIcon, PlayIcon } from "@phosphor-icons/react";

import { type EngineeringUnit, NumericUnitInput } from "@/components/ui/NumericUnitInput";
import { engineering } from "@/lib/format";
import { formatCriterionDefinition, formatExperimentType, getParameterReferenceLabel, getParameterUnit } from "@/lib/presentation";
import type { Circuit, Experiment, ExperimentCriterion, ExperimentDefinition, ExperimentVariable } from "@/lib/types";

type BuilderTab = "setup" | "variables" | "measurements" | "criteria" | "runs" | "review";
type GeneratedRun = { index: number; values: Record<string, number>; enabled: boolean };
const MAX_RUNS = 5_000;
const baseMeasurementOptions = [{ id: "Output Voltage", description: "Voltage measured from the Output probe to Ground", quantity: "Voltage", unit: "V" }, { id: "AC Gain", description: "Derived small-signal gain at the configured frequency", quantity: "Gain", unit: "dB" }];
const parameterKey = (variable: Pick<ExperimentVariable, "component_id" | "parameter">) => `${variable.component_id}.${variable.parameter}`;
const unitsFor = (unit: string): EngineeringUnit[] => unit === "Ω" ? [{ label: "MΩ", multiplier: 1e6 }, { label: "kΩ", multiplier: 1e3 }, { label: "Ω", multiplier: 1 }] : unit === "F" ? [{ label: "mF", multiplier: 1e-3 }, { label: "µF", multiplier: 1e-6 }, { label: "nF", multiplier: 1e-9 }, { label: "pF", multiplier: 1e-12 }] : unit === "H" ? [{ label: "H", multiplier: 1 }, { label: "mH", multiplier: 1e-3 }, { label: "µH", multiplier: 1e-6 }] : unit === "V" ? [{ label: "kV", multiplier: 1e3 }, { label: "V", multiplier: 1 }, { label: "mV", multiplier: 1e-3 }] : unit === "dB" ? [{ label: "dB", multiplier: 1 }] : [{ label: unit || "base", multiplier: 1 }];
const criterionUnit = (metric: string) => metric === "AC Gain" ? "dB" : "V";

function sweepValues(variable: ExperimentVariable) {
  if (variable.sweep === "explicit") return (variable.values ?? []).filter(Number.isFinite);
  if (variable.points < 2 || !Number.isFinite(variable.start) || !Number.isFinite(variable.stop) || variable.start >= variable.stop || (variable.sweep === "logarithmic" && variable.start <= 0)) return [];
  return Array.from({ length: variable.points }, (_, index) => variable.sweep === "logarithmic" ? variable.start * Math.pow(variable.stop / variable.start, index / (variable.points - 1)) : variable.start + ((variable.stop - variable.start) * index) / (variable.points - 1));
}

function makeMatrix(variables: ExperimentVariable[], disabled: Set<number>): GeneratedRun[] {
  const lists = variables.map(sweepValues);
  if (!lists.length || lists.some((list) => !list.length)) return [];
  if (lists.reduce((total, list) => total * list.length, 1) > MAX_RUNS) return [];
  const runs: GeneratedRun[] = [];
  const build = (depth: number, current: Record<string, number>) => {
    if (depth === variables.length) { const index = runs.length + 1; runs.push({ index, values: current, enabled: !disabled.has(index) }); return; }
    lists[depth].forEach((value) => build(depth + 1, { ...current, [parameterKey(variables[depth])]: value }));
  };
  build(0, {});
  return runs;
}

function CriterionEditor({ criterion, immutable, measurements, onChange, onRemove }: { criterion: ExperimentCriterion; immutable: boolean; measurements: string[]; onChange: (criterion: ExperimentCriterion) => void; onRemove: () => void }) {
  const unit = criterionUnit(criterion.metric);
  const bounds: [number, number] = Array.isArray(criterion.target) ? criterion.target : [Number(criterion.target), Number(criterion.target)];
  const setOperator = (operator: ExperimentCriterion["operator"]) => {
    if (operator === "between") onChange({ ...criterion, operator, target: Array.isArray(criterion.target) ? criterion.target : [Number(criterion.target), Number(criterion.target)] });
    else if (operator === "approximately") onChange({ ...criterion, operator, target: Array.isArray(criterion.target) ? criterion.target[0] : criterion.target, tolerance: criterion.tolerance ?? 0 });
    else onChange({ ...criterion, operator, target: Array.isArray(criterion.target) ? criterion.target[0] : criterion.target, tolerance: undefined });
  };
  return <div className="criterion-row">
    <label>Measurement<select disabled={immutable} onChange={(event) => onChange({ ...criterion, metric: event.target.value })} value={criterion.metric}>{measurements.map((item) => <option key={item}>{item}</option>)}</select></label>
    <label>Condition<select disabled={immutable} onChange={(event) => setOperator(event.target.value as ExperimentCriterion["operator"])} value={criterion.operator}><option value=">=">Minimum</option><option value="<=">Maximum</option><option value="between">Between</option><option value="approximately">Target ± tolerance</option></select></label>
    <div className="criterion-values">{criterion.operator === "between" ? <><label>Minimum<NumericUnitInput ariaLabel={`${criterion.metric} minimum`} disabled={immutable} onCommit={(value) => onChange({ ...criterion, target: [value, bounds[1]] })} units={unitsFor(unit)} value={bounds[0]} /></label><label>Maximum<NumericUnitInput ariaLabel={`${criterion.metric} maximum`} disabled={immutable} onCommit={(value) => onChange({ ...criterion, target: [bounds[0], value] })} units={unitsFor(unit)} value={bounds[1]} /></label></> : <><label>{criterion.operator === "approximately" ? "Target" : "Value"}<NumericUnitInput ariaLabel={`${criterion.metric} value`} disabled={immutable} onCommit={(value) => onChange({ ...criterion, target: value })} units={unitsFor(unit)} value={Number(criterion.target)} /></label>{criterion.operator === "approximately" ? <label>Tolerance<NumericUnitInput ariaLabel={`${criterion.metric} tolerance`} disabled={immutable} onCommit={(value) => onChange({ ...criterion, tolerance: Math.abs(value) })} units={unitsFor(unit)} value={criterion.tolerance ?? 0} /></label> : null}</>}</div>
    <button className="button button--tertiary" disabled={immutable} onClick={onRemove} type="button">Remove</button>
    <p className="criterion-expression">{criterion.metric}: {formatCriterionDefinition(criterion)}</p>
  </div>;
}

export function ExperimentBuilder({ circuit, initial, collectionOptions = [], onCancel, onSave }: { circuit: Circuit; initial?: Experiment | null; collectionOptions?: string[]; onCancel: () => void; onSave: (definition: ExperimentDefinition, runAfterSave?: boolean) => void }) {
  const measurementOptions = useMemo(() => [...baseMeasurementOptions, ...circuit.components.filter((component) => component.type !== "ground").map((component) => ({ id: `Branch Current:${component.id}`, description: `Actual ngspice branch current through ${component.id}`, quantity: "Current", unit: "A" }))], [circuit.components]);
  const [tab, setTab] = useState<BuilderTab>("setup");
  const [name, setName] = useState(initial?.name ?? "New experiment");
  const [description, setDescription] = useState(initial?.description ?? "");
  const [collectionName, setCollectionName] = useState(initial?.collection_name ?? "");
  const [runBy, setRunBy] = useState(initial?.run_by ?? "");
  const [notes, setNotes] = useState(initial?.notes ?? "");
  const [type, setType] = useState<ExperimentDefinition["experiment_type"]>((initial?.experiment_type as ExperimentDefinition["experiment_type"]) ?? "characterization");
  const [variables, setVariables] = useState<ExperimentVariable[]>(() => (initial?.variables ?? []).map((variable) => ({ ...variable, label: getParameterReferenceLabel(variable.component_id, variable.parameter) })));
  const [measurements, setMeasurements] = useState<string[]>(initial?.measurement_definitions?.length ? initial.measurement_definitions.filter((measurement) => measurementOptions.some((option) => option.id === measurement)) : ["Output Voltage"]);
  const [criteria, setCriteria] = useState<ExperimentCriterion[]>(() => initial?.requirement_definitions?.map((criterion) => ({ ...criterion })) ?? []);
  const [disabledRuns, setDisabledRuns] = useState<Set<number>>(() => new Set(initial?.generated_runs?.filter((run) => run.enabled === false).map((run) => run.index) ?? []));
  const immutable = Boolean(initial?.run_results?.length);
  const available = useMemo(() => circuit.components.flatMap((component) => Object.entries(component.params).filter((entry): entry is [string, number] => typeof entry[1] === "number").map(([parameter, value]) => ({ component_id: component.id, parameter, value, unit: getParameterUnit(parameter), label: getParameterReferenceLabel(component.id, parameter) }))), [circuit]);
  const total = variables.length ? variables.reduce((product, variable) => product * sweepValues(variable).length, 1) : 0;
  const invalidSweep = variables.some((variable) => !sweepValues(variable).length);
  const tooLarge = total > MAX_RUNS;
  const runs = useMemo(() => makeMatrix(variables, disabledRuns), [disabledRuns, variables]);
  const ready = Boolean(name.trim() && variables.length && measurements.length && !invalidSweep && !tooLarge);
  const updateVariable = (index: number, patch: Partial<ExperimentVariable>) => setVariables((current) => current.map((variable, currentIndex) => currentIndex === index ? { ...variable, ...patch } : variable));
  const toggleVariable = (item: typeof available[number]) => setVariables((current) => {
    const exists = current.some((variable) => parameterKey(variable) === `${item.component_id}.${item.parameter}`);
    if (exists) return current.filter((variable) => parameterKey(variable) !== `${item.component_id}.${item.parameter}`);
    if (current.length >= 2) return current;
    const span = Math.abs(item.value) || 1;
    return [...current, { component_id: item.component_id, parameter: item.parameter, label: item.label, unit: item.unit, sweep: "linear", start: item.value > 0 ? item.value / 2 : item.value - span, stop: item.value > 0 ? item.value * 2 : item.value + span, points: 5 }];
  });
  const toggleMeasurement = (measurement: string) => {
    const removing = measurements.includes(measurement);
    setMeasurements((current) => removing ? current.filter((value) => value !== measurement) : [...current, measurement]);
    if (removing) setCriteria((current) => current.filter((criterion) => criterion.metric !== measurement));
  };
  const definition: ExperimentDefinition = { name, description, experiment_type: type, circuit_revision: circuit.revision, variables, measurement_definitions: measurements, requirement_definitions: criteria, generated_runs: runs, collection_name: collectionName, run_by: runBy, notes };
  const initialDefinition = useMemo(() => ({ name: initial?.name ?? "New experiment", description: initial?.description ?? "", collection_name: initial?.collection_name ?? "", run_by: initial?.run_by ?? "", notes: initial?.notes ?? "", experiment_type: initial?.experiment_type ?? "characterization", variables: initial?.variables ?? [], measurement_definitions: initial?.measurement_definitions?.length ? initial.measurement_definitions : ["Output Voltage"], requirement_definitions: initial?.requirement_definitions ?? [], generated_runs: initial?.generated_runs ?? [] }), [initial]);
  const dirty = !immutable && JSON.stringify({ ...definition, circuit_revision: undefined }) !== JSON.stringify(initialDefinition);
  const requestCancel = () => { if (!dirty || window.confirm("Discard unsaved experiment changes?")) onCancel(); };

  return <section className="experiment-builder">
    <header className="builder-header"><div><button className="builder-back" onClick={requestCancel} type="button"><ArrowLeftIcon aria-hidden size={14} />Experiments</button><h2>{name || "Untitled experiment"}</h2><span>{circuit.name} / Revision {circuit.revision}{dirty ? " / Unsaved changes" : ""}</span></div><div>{immutable ? <span className="builder-immutable">Recorded experiment</span> : <><button className="button button--secondary" onClick={requestCancel} type="button">Cancel</button><button className="button button--secondary" disabled={!name.trim()} onClick={() => onSave(definition)} type="button">Save Draft</button></>}</div></header>
    {immutable && <p className="builder-immutable-note">This recorded experiment is read-only so its configuration remains reproducible.</p>}
    <nav aria-label="Experiment builder" className="builder-tabs" role="tablist">{([ ["setup", "Setup"], ["variables", "Variables"], ["measurements", "Measurements"], ["criteria", "Requirements"], ["runs", "Runs"], ["review", "Review"] ] as const).map(([id, label]) => <button aria-selected={tab === id} className={tab === id ? "is-active" : ""} key={id} onClick={() => setTab(id)} role="tab" type="button">{label}</button>)}</nav>
    <div className="builder-layout"><main className="builder-content">
      {tab === "setup" && <section className="builder-step"><header><h3>Experiment setup</h3><p>Name the test, identify the operator, and capture the intended record.</p></header><div className="builder-form"><label>Experiment name<input disabled={immutable} onChange={(event) => setName(event.target.value)} value={name} /></label><label>Collection<input disabled={immutable} list="experiment-collections" onChange={(event) => setCollectionName(event.target.value)} placeholder="e.g. Filter characterization" value={collectionName} /><small>Optional. Type a new name or choose an existing collection.</small></label><datalist id="experiment-collections">{collectionOptions.map((collection) => <option key={collection} value={collection} />)}</datalist><label>Run by<input disabled={immutable} onChange={(event) => setRunBy(event.target.value)} placeholder="Name or team" value={runBy} /></label><label>Purpose<textarea disabled={immutable} onChange={(event) => setDescription(event.target.value)} placeholder="Describe what this experiment should establish." value={description} /></label><label>Run notes / comments<textarea disabled={immutable} onChange={(event) => setNotes(event.target.value)} placeholder="Context, setup observations, or handoff notes." value={notes} /></label><label>Experiment type<select disabled={immutable} onChange={(event) => setType(event.target.value as ExperimentDefinition["experiment_type"])} value={type}>{["characterization", "validation", "optimization", "robustness", "manual"].map((item) => <option key={item} value={item}>{formatExperimentType(item)}</option>)}</select></label><div className="revision-note"><span>Circuit under test</span><strong>{circuit.name}</strong><small>Revision {circuit.revision}. The saved experiment remains attached to this circuit snapshot.</small></div></div></section>}
      {tab === "variables" && <section className="builder-step"><header><h3>Variables</h3><p>Select up to two circuit parameters and configure their sweep ranges.</p></header><div className="variable-layout"><section className="parameter-selection"><h4>Available parameters</h4>{available.map((item) => { const checked = variables.some((variable) => parameterKey(variable) === `${item.component_id}.${item.parameter}`); return <label className="selection-row" key={`${item.component_id}.${item.parameter}`}><input checked={checked} disabled={immutable || (!checked && variables.length >= 2)} onChange={() => toggleVariable(item)} type="checkbox" /><span><b>{item.label}</b><small>Current value: {engineering(item.value, item.unit)}</small></span></label>; })}</section><section className="sweep-configuration"><h4>Sweep configuration</h4>{variables.length ? variables.map((variable, index) => <div className="sweep-row" key={parameterKey(variable)}><div className="sweep-row__heading"><b>{variable.label}</b><span>{sweepValues(variable).length} values</span></div><label>Sweep<select disabled={immutable} onChange={(event) => updateVariable(index, { sweep: event.target.value as ExperimentVariable["sweep"] })} value={variable.sweep}><option value="linear">Linear</option><option value="logarithmic">Logarithmic</option><option value="explicit">Explicit values</option></select></label>{variable.sweep === "explicit" ? <label>Values<input disabled={immutable} onChange={(event) => updateVariable(index, { values: event.target.value.split(",").map((value) => Number(value.trim())).filter(Number.isFinite) })} placeholder="1, 2.2, 4.7" value={variable.values?.join(", ") ?? ""} /></label> : <div className="sweep-row__values"><label>Start<NumericUnitInput ariaLabel={`${variable.label} start`} disabled={immutable} onCommit={(value) => updateVariable(index, { start: value })} units={unitsFor(variable.unit)} value={variable.start} /></label><label>Stop<NumericUnitInput ariaLabel={`${variable.label} stop`} disabled={immutable} onCommit={(value) => updateVariable(index, { stop: value })} units={unitsFor(variable.unit)} value={variable.stop} /></label><label className="point-input">Points<input disabled={immutable} min="2" onChange={(event) => updateVariable(index, { points: Math.max(2, Math.round(Number(event.target.value) || 2)) })} type="number" value={variable.points} /></label></div>}</div>) : <p className="builder-empty-copy">Select a parameter to configure its sweep.</p>}</section></div><div className={`run-count ${tooLarge ? "is-warning" : ""}`}><span>{variables.map((variable) => sweepValues(variable).length).join(" × ") || "0"} combinations</span><strong>{total.toLocaleString()} planned runs</strong>{invalidSweep && <small>Each sweep needs a valid start, stop, and at least two values.</small>}{tooLarge && <small>Reduce the plan to {MAX_RUNS.toLocaleString()} runs or fewer.</small>}</div></section>}
      {tab === "measurements" && <section className="builder-step"><header><h3>Measurements</h3><p>Choose the quantities recorded for every completed run.</p></header><div className="measurement-options">{measurementOptions.map((item) => <label className="measurement-option" key={item.id}><input checked={measurements.includes(item.id)} disabled={immutable} onChange={() => toggleMeasurement(item.id)} type="checkbox" /><span><b>{item.id}</b><small>{item.description}</small></span><dl><div><dt>Quantity</dt><dd>{item.quantity}</dd></div><div><dt>Unit</dt><dd>{item.unit}</dd></div></dl></label>)}</div><p className="selection-count">{measurements.length} measurement{measurements.length === 1 ? "" : "s"} selected</p></section>}
      {tab === "criteria" && <section className="builder-step"><header><h3>Requirements</h3><p>Optional. Runs are classified as passing or failing only when requirements are defined.</p></header><div className="criteria-list">{criteria.map((criterion, index) => <CriterionEditor criterion={criterion} immutable={immutable} key={`${criterion.metric}-${index}`} measurements={measurements} onChange={(next) => setCriteria((current) => current.map((item, itemIndex) => itemIndex === index ? next : item))} onRemove={() => setCriteria((current) => current.filter((_, itemIndex) => itemIndex !== index))} />)}</div>{criteria.length ? null : <div className="builder-empty-state"><strong>No requirements defined</strong><p>Runs will still record measurements, but no pass or fail result will be assigned.</p></div>}<button className="button button--secondary" disabled={immutable || !measurements.length} onClick={() => setCriteria((current) => [...current, { metric: measurements[0] ?? "Output Voltage", operator: ">=", target: 0 }])} type="button">Add requirement</button></section>}
      {tab === "runs" && <section className="builder-step"><header><h3>Run matrix</h3><p>Review every sampled combination. Disable any configuration that should not be executed.</p></header>{runs.length ? <div className="run-table-wrap"><table className="run-table data-table"><thead><tr><th>Enabled</th><th>Run</th>{variables.map((variable) => <th key={variable.label}>{variable.label}</th>)}</tr></thead><tbody>{runs.slice(0, 250).map((run) => <tr key={run.index}><td><input aria-label={`Enable run ${run.index}`} checked={run.enabled} disabled={immutable} onChange={() => setDisabledRuns((current) => { const next = new Set(current); if (next.has(run.index)) next.delete(run.index); else next.add(run.index); return next; })} type="checkbox" /></td><td className="numeric-column">{String(run.index).padStart(3, "0")}</td>{variables.map((variable) => <td className="numeric-column" key={variable.label}>{engineering(run.values[parameterKey(variable)], variable.unit)}</td>)}</tr>)}</tbody></table>{runs.length > 250 ? <p className="builder-inline-note">Showing the first 250 of {runs.length.toLocaleString()} planned runs.</p> : null}</div> : <div className="builder-empty-state"><strong>No runs generated</strong><p>Configure at least one valid variable sweep to generate the run matrix.</p></div>}</section>}
      {tab === "review" && <section className="builder-step review-step"><header><h3>Review experiment</h3><p>Confirm the circuit, sweep plan, measurements, and requirements before execution.</p></header><dl className="review-summary"><div><dt>Circuit</dt><dd>{circuit.name}<small>Revision {circuit.revision}</small></dd></div><div><dt>Variables</dt><dd>{variables.length ? variables.map((variable) => <span key={parameterKey(variable)}><b>{variable.label}</b>{engineering(variable.start, variable.unit)} to {engineering(variable.stop, variable.unit)}, {sweepValues(variable).length} values</span>) : "Not configured"}</dd></div><div><dt>Measurements</dt><dd>{measurements.join(", ") || "Not configured"}</dd></div><div><dt>Requirements</dt><dd>{criteria.length ? criteria.map((criterion, index) => <span key={index}><b>{criterion.metric}</b>{formatCriterionDefinition(criterion)}</span>) : "None"}</dd></div></dl><div className="review-total"><div><strong>{total.toLocaleString()}</strong><span>planned runs / {variables.map((variable) => sweepValues(variable).length).join(" × ")} combinations / {runs.filter((run) => run.enabled).length} enabled</span></div><button className="button button--secondary" disabled={!runs.length} onClick={() => setTab("runs")} type="button">Review Runs</button></div><div className="review-action">{ready ? <span><CheckCircleIcon aria-hidden size={16} />{immutable ? "Recorded configuration" : "Ready to run"}</span> : <span>Complete the required setup before execution.</span>}{!immutable && <div className="review-action__buttons"><button className="button button--secondary" disabled={!ready} onClick={() => onSave(definition)} type="button">Save Experiment</button><button className="button button--primary" disabled={!ready} onClick={() => onSave(definition, true)} type="button"><PlayIcon aria-hidden size={14} />Save and Run</button></div>}</div></section>}
    </main><aside className="builder-summary"><h3>Experiment summary</h3><dl><div><dt>Type</dt><dd>{formatExperimentType(type)}</dd></div><div><dt>Variables</dt><dd>{variables.length}</dd></div><div><dt>Measurements</dt><dd>{measurements.length}</dd></div><div><dt>Requirements</dt><dd>{criteria.length}</dd></div><div><dt>Planned runs</dt><dd>{total.toLocaleString()}</dd></div></dl><p className={ready ? "is-ready" : ""}>{ready ? <><CheckCircleIcon aria-hidden size={15} />{immutable ? "Recorded configuration" : "Ready to run"}</> : "Setup incomplete"}</p></aside></div>
  </section>;
}
