export type ComponentType = "ground" | "resistor" | "capacitor" | "inductor" | "voltage_source" | "diode" | "ideal_opamp";
export type ParameterValue = number | string | boolean;
export type CircuitComponent = { id: string; type: ComponentType; params: Record<string, ParameterValue>; pins: Record<string, string | null>; position?: { x: number; y: number } | null; rotation?: 0 | 90 | 180 | 270 };
export type CircuitNode = { id: string; label: string };
export type Circuit = { id: string; revision: number; name: string; components: CircuitComponent[]; nodes: CircuitNode[]; metadata: Record<string, string> };
export type Constraint = { id: string; metric: string; operator: "<" | "<=" | ">" | ">=" | "between" | "approximately"; target: number | [number, number]; tolerance?: number | null };
export type ConstraintResult = { constraint_id: string; status: "PASS" | "FAIL" | "NOT_EVALUATED"; actual: number | null; target: number | [number, number]; message: string };
export type Challenge = { id: string; title: string; description: string; component_limit: number; allowed_components: ComponentType[]; constraints: Constraint[] };
export type ChallengeSummary = Pick<Challenge, "id" | "title" | "description">;
export type SimulationResult = { success: boolean; analysis: "operating_point" | "ac" | "transient"; circuit_revision: number; simulation_id: string; measurements: Record<string, number>; series: Record<string, number[]>; warnings: string[]; errors: Array<{ code: string; message: string; details?: string }> };
export type ExperimentRequirementResult = { metric: string; operator?: string; status: "PASS" | "FAIL" | "UNAVAILABLE"; actual: number | null; target: number | [number, number] | null };
export type ExperimentRunResult = { run_index: number; status: string; parameters: Record<string, number>; measurements?: Record<string, number>; requirement_results?: ExperimentRequirementResult[]; error?: string | null; started_at?: string | null; completed_at?: string | null; run_by?: string; notes?: string };
export type ExperimentCriterion = { metric: string; operator: ">=" | "<=" | "between" | "approximately"; target: number | [number, number]; tolerance?: number };
export type Experiment = { id: string; sequence: number; created_at: string; hypothesis: string; conclusion: string; circuit_revision: number; circuit_snapshot: Circuit; simulation_ids: string[]; measurements: Record<string, number>; constraint_results: ConstraintResult[]; name?: string | null; description?: string; experiment_type?: string; status?: string; execution_status?: "draft" | "ready" | "running" | "paused" | "completed" | "failed" | "interrupted"; variables?: ExperimentVariable[]; measurement_definitions?: string[]; requirement_definitions?: ExperimentCriterion[]; generated_runs?: Array<{ index: number; enabled?: boolean; values?: Record<string, number> }>; run_results?: ExperimentRunResult[]; started_at?: string | null; completed_at?: string | null; collection_name?: string; run_by?: string; notes?: string };
export type SweepKind = "linear" | "logarithmic" | "explicit";
export type ExperimentVariable = { component_id: string; parameter: string; label: string; unit: string; sweep: SweepKind; start: number; stop: number; points: number; values?: number[] };
export type ExperimentDefinition = { name: string; description: string; experiment_type: "characterization" | "validation" | "optimization" | "robustness" | "manual"; circuit_revision: number; variables: ExperimentVariable[]; measurement_definitions: string[]; requirement_definitions: ExperimentCriterion[]; generated_runs: Array<{ index: number; values: Record<string, number>; enabled: boolean }>; collection_name: string; run_by: string; notes: string };
export type SavedCircuitSummary = { id: string; name: string; created_at: string; updated_at: string; component_count: number; active: boolean };
export type LabState = { challenge: Challenge; circuit: Circuit; latest_experiment: Experiment | null; active_saved_circuit_id: string | null };
export type ConstraintEvaluation = { all_pass: boolean; passed: number; failed: number; not_evaluated: number; results: ConstraintResult[] };
export type EvaluationResponse = { measurements: Record<string, number>; evaluation: ConstraintEvaluation };
export type ValidationResponse = { valid: boolean; issues: Array<{ code: string; message: string; recovery_hint?: string | null }> };
export type WebMCPDefinition = { name: string; description: string; input_schema: Record<string, unknown>; read_only: boolean };
